-dontwarn com.caverock.androidsvg.SVG
-dontwarn com.caverock.androidsvg.SVGParseException
-dontwarn pl.droidsonroids.gif.GifDrawable
-dontwarn java.lang.invoke.StringConcatFactory
-keep class com.trx.habitmeta.common.** { *; }
-keep class com.trx.habitmeta.shared.** { *; }
